# Site settings
title: taglich
email: taglich.official@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://mailchi.mp/f3d08dd10b08/taglich

# User setting
owner: taglich
email: taglich.official@gmail.com
facebook_username: taglich.official
github_username: https://github.com/carinamogos/taglich
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown
